FROM debian:12

# Install build tools
RUN apt update
RUN apt install -y build-essential cmake wget git gawk libzstd-dev pkg-config clang tar
RUN apt install -y python3-venv python3-dev

RUN wget https://www.doxygen.nl/files/doxygen-1.16.1.linux.bin.tar.gz
RUN tar -xvf doxygen-1.16.1.linux.bin.tar.gz
RUN cd doxygen-1.16.1 && make install && cd .. && rm -rf doxygen*

RUN python3 -m venv /opt/venv
ENV VIRTUAL_ENV="/opt/venv"
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install python-dev-tools pybind11