FROM debian:12

# Install build tools
RUN apt update \
  && apt install -y build-essential cmake wget git gawk libzstd-dev pkg-config clang python3-venv doxygen

RUN python3 -m venv /opt/venv
ENV VIRTUAL_ENV="/opt/venv"
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install python-dev-tools pybind11