# Build the python packages
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.20
        env:
          CIBW_SKIP: "pp* *_i686"
          CIBW_BEFORE_BUILD_LINUX: "yum install -y libzstd-devel || apt-get install -y libzstd-dev || apk add zstd-dev"
          CIBW_BEFORE_BUILD_MACOS: "brew install zstd"
      - uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl
