# Build the python packages
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libzstd-dev
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install zstd
      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          vcpkg install zstd
      - uses: pypa/cibuildwheel@v2.20
      - uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl
