---
name: CMake_tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BUILD_TYPE: RelWithDebInfo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        with:
          packages: build-essential cmake wget git gawk libzstd-dev libjsoncpp-dev pkg-config

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_OTF2=ON<w
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  unit_test:
     need: build
     steps:
       - name: Test
         working-directory: ${{github.workspace}}/build
         run: ctest -C ${{env.BUILD_TYPE}}
