---
name: Validation_tests
on:
  workflow_dispatch:
env:
  BUILD_TYPE: RelWithDebInfo
jobs:
  build:
    runs-on: ubuntu-latest
    container: ftrahay/htf:test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure HTF
        run: cmake -B ${{github.workspace}}/build --prefix=${{github.workspace}}/install -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_OTF2=ON -DENABLE_ZFP=ON -DENABLE_SZ=ON

      - name: Build HTF
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Install HTF
        run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Unit Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
